import ekf_class

ekf = ekf_class.ExtendedKalmanFilter()
print(ekf.get_x_est())
print(ekf.get_p_mat())
ekf.prediction()
print(ekf.get_x_est())
print(ekf.get_p_mat())

ekf.update(1, 0.5, 0.5)
print(ekf.get_z_est(0.5, 0.5))
print(ekf.get_x_est())
print(ekf.get_p_mat())
ekf.prediction()
ekf.update(1, 0.5, 0.5)
print(ekf.get_z_est(0.5, 0.5))
print(ekf.get_x_est())
print(ekf.get_p_mat())
ekf.prediction()
print(ekf.get_p_mat())
ekf.update(1, 0.5, 0.5)
print(ekf.get_z_est(0.5, 0.5))
print(ekf.get_x_est())
print(ekf.get_p_mat())
ekf.prediction()
ekf.update(1, 0.5, 0.5)
print(ekf.get_z_est(0.5, 0.5))
print(ekf.get_x_est())
print(ekf.get_p_mat())
ekf.prediction()
ekf.update(1, 0.5, 0.5)
print(ekf.get_z_est(0.5, 0.5))
print(ekf.get_x_est())
print(ekf.get_p_mat())

print(ekf.get_z_est(0.5, 0.5))
