import ekf_class

ekf = ekf_class.ExtendedKalmanFilter()
print(ekf.get_x_est())
print(ekf.get_p_mat())
ekf.prediction()
print(ekf.get_x_est())
print(ekf.get_p_mat())

ekf.update(1)
print(ekf.get_x_est())
print(ekf.get_p_mat())
ekf.prediction()
ekf.update(1)
print(ekf.get_x_est())
print(ekf.get_p_mat())
ekf.prediction()
print(ekf.get_p_mat())
ekf.update(1)
print(ekf.get_x_est())
print(ekf.get_p_mat())
ekf.prediction()
ekf.update(1)
print(ekf.get_x_est())
print(ekf.get_p_mat())
ekf.prediction()
ekf.update(1)
print(ekf.get_x_est())
print(ekf.get_p_mat())